# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

import os
import sys
from pathlib import Path

# Add the src directory to Python path for autodoc
project_root = Path(__file__).parent.parent
src_path = project_root / 'src'
sys.path.insert(0, str(src_path))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Bewerbung Generator'
copyright = '2025, Thomas Michael Setz'
author = 'Thomas Michael Setz'
release = '1.0.0'
version = '1.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',           # Automatic documentation from docstrings
    'sphinx.ext.autosummary',       # Generate summary tables
    'sphinx.ext.napoleon',          # Support for Google and NumPy style docstrings
    'sphinx.ext.viewcode',          # Add source code links
    'sphinx.ext.intersphinx',       # Link to other project's documentation
    'sphinx.ext.doctest',           # Test code snippets in docstrings
    'sphinx.ext.coverage',          # Check documentation coverage
    'sphinx.ext.githubpages',       # GitHub Pages support
    'sphinx_autodoc_typehints',     # Type hints support
    'myst_parser',                  # Markdown support
    'sphinx_copybutton',            # Copy button for code blocks
    'sphinxext.opengraph',          # Enhanced GitHub integration
    'sphinxcontrib.mermaid',        # Mermaid diagram support
]

# Add support for Markdown files
source_suffix = {
    '.rst': None,
    '.md': None,
}

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'furo'
html_title = f"{project} Documentation"
html_short_title = project

html_static_path = ['_static']

# Furo theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_button": "edit",
    "source_repository": "https://github.com/thsetz/Bewerbung/",
    "source_branch": "main",
    "source_directory": "docs/",
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/thsetz/Bewerbung",
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            """,
            "class": "",
        },
    ],
}

# Custom CSS and JS files
html_css_files = []
html_js_files = []

# -- Options for autodoc ----------------------------------------------------

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Include type hints in documentation
autodoc_typehints = 'description'
autodoc_typehints_description_target = 'documented'

# -- Options for autosummary ------------------------------------------------

autosummary_generate = True
autosummary_imported_members = True

# -- Options for napoleon ---------------------------------------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for intersphinx ------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'jinja2': ('https://jinja.palletsprojects.com/', None),
    'requests': ('https://requests.readthedocs.io/en/stable/', None),
    'pytest': ('https://docs.pytest.org/en/stable/', None),
}

# -- Options for MyST parser ------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# -- Options for copy button ------------------------------------------------

copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_exclude = '.linenos, .gp, .go'

# -- Options for coverage ---------------------------------------------------

coverage_show_missing_items = True

# -- Options for doctest ----------------------------------------------------

doctest_global_setup = '''
import sys
sys.path.insert(0, '../src')
'''

# -- Options for Mermaid ----------------------------------------------------

mermaid_version = "10.6.1"
mermaid_init_js = """
mermaid.initialize({
    startOnLoad: true,
    theme: 'default',
    flowchart: {
        curve: 'basis',
        htmlLabels: true
    },
    sequence: {
        actorMargin: 50,
        width: 150
    }
});
"""

# -- Options for OpenGraph --------------------------------------------------

ogp_site_url = "https://thsetz.github.io/Bewerbung/"
ogp_site_name = "Bewerbung Generator Documentation"
ogp_description = "Professional application document generator with AI support"
ogp_type = "website"
ogp_image = "https://raw.githubusercontent.com/thsetz/Bewerbung/main/docs/_static/logo.png"